version: '2'
services:
  chatbot_walle:
    build: chatbot
    image: chatbot
    command: python server.py --name WallE --host 0.0.0.0 --port 5002 --bot Math --workdir /tmp/
    volumes:
     - ./chatbot:/app
    network_mode: host
    ports:
     - "5002:5002"
    expose:
     - "5002"
  chatbot_hal9000:
    build: chatbot
    image: chatbot
    command: python server.py --name HAL9000 --host 0.0.0.0 --port 5003 --bot Zen --workdir /tmp/
    volumes:
     - ./chatbot:/app
    network_mode: host
    ports:
     - "5003:5003"
    expose:
     - "5003"
  slackbot_cli:
    build: slackbot
    image: slackbot
    command: python bot_cli.py --chatservice_host 0.0.0.0 --slackbot_host 0.0.0.0 --port 5001
    volumes:
     - ./slackbot:/app
    ports:
     - "5001:5001"
    network_mode: host
    environment:
     - SLACK_BOT_TOKEN=UNDEFINED
  slackbot_slack:
    build: slackbot
    image: slackbot
    command: python bot_slack.py --chatservice_host 0.0.0.0
    volumes:
     - ./slackbot:/app
    ports:
     - "5001:5001"
    network_mode: host
    environment:
     - SLACK_BOT_TOKEN=UNDEFINED
